### ISSUE TITLE
Dumbest shit

### ISSUE THREAD

**Issue by sandyy-gmod** [FLUORESCENTXX/Discord-Image-Logger#2]
You cannot make image malware, it won't execute, Can't just write executable code into a nonexecutable???!?!?

**Comment by FLUORESCENTXX** [comment]
u can write one yourself but this is hiding one in an image and it is possible.

**Comment by cChimney** [comment]
> u can write one yourself but this is hiding one in an image and it is possible.

yes it's having exe code in a jpg which "hides" it but u can't execute it while its a .jpg 🤡
